dependencies {
    implementation(project(":simplified-accounts-api"))
    implementation(project(":simplified-bookmarks-api"))
    implementation(project(":simplified-books-api"))
    implementation(project(":simplified-books-database-api"))
    implementation(project(":simplified-books-formats-api"))
    implementation(project(":simplified-files"))
    implementation(project(":simplified-json-core"))
    implementation(project(":simplified-opds-core"))

    implementation(libs.google.failureaccess)
    implementation(libs.google.guava)
    implementation(libs.io7m.jnull)
    implementation(libs.irradia.mime.api)
    implementation(libs.jackson.core)
    implementation(libs.jackson.databind)
    implementation(libs.jcip.annotations)
    implementation(libs.joda.time)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.stdlib)
    implementation(libs.palace.audiobook.api)
    implementation(libs.palace.audiobook.manifest.api)
    implementation(libs.palace.audiobook.manifest.parser.api)
    implementation(libs.palace.audiobook.parser.api)
    implementation(libs.palace.drm.core)
    implementation(libs.slf4j)
}
