dependencies {
    implementation(project(":simplified-android-ktx"))
    implementation(project(":simplified-presentableerror-api"))
    implementation(project(":simplified-reports"))
    implementation(project(":simplified-taskrecorder-api"))
    implementation(project(":simplified-ui-listeners-api"))
    implementation(project(":simplified-ui-neutrality"))

    implementation(libs.androidx.activity)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.cardview)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.coordinatorlayout)
    implementation(libs.androidx.core)
    implementation(libs.androidx.customview)
    implementation(libs.androidx.drawerlayout)
    implementation(libs.androidx.fragment)
    implementation(libs.androidx.lifecycle.common)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.androidx.preference)
    implementation(libs.androidx.recycler.view)
    implementation(libs.androidx.savedstate)
    implementation(libs.google.material)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.stdlib)
    implementation(libs.slf4j)
}
