dependencies {
    implementation(project(":simplified-accessibility"))
    implementation(project(":simplified-analytics-api"))
    implementation(project(":simplified-bookmarks-api"))
    implementation(project(":simplified-feeds-api"))
    implementation(project(":simplified-futures"))
    implementation(project(":simplified-services-api"))
    implementation(project(":simplified-ui-thread-api"))
    implementation(project(":simplified-viewer-spi"))

    implementation(libs.androidx.activity)
    implementation(libs.androidx.app.compat)
    implementation(libs.androidx.lifecycle)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.stdlib)
    implementation(libs.palace.drm.core)
    implementation(libs.palace.readium2.api)
    implementation(libs.palace.readium2.vanilla)
    implementation(libs.palace.readium2.views)
    implementation(libs.slf4j)
    implementation(libs.transifex.sdk)
}
