dependencies {
    coreLibraryDesugaring(libs.android.desugaring)

    implementation(project(":simplified-accounts-api"))
    implementation(project(":simplified-accounts-database-api"))
    implementation(project(":simplified-crashlytics-api"))
    implementation(project(":simplified-json-core"))
    implementation(project(":simplified-profiles-api"))
    implementation(project(":simplified-profiles-controller-api"))
    implementation(project(":simplified-services-api"))

    implementation(libs.azam.ulidj)
    implementation(libs.io7m.jmulticlose)
    implementation(libs.io7m.jattribute.core)
    implementation(libs.irradia.mime.api)
    implementation(libs.jackson.core)
    implementation(libs.jackson.databind)
    implementation(libs.joda.time)
    implementation(libs.kotlin.stdlib)
    implementation(libs.kotlinx.datetime)
    implementation(libs.palace.audiobook.api)
    implementation(libs.palace.audiobook.manifest.api)
    implementation(libs.palace.audiobook.time.tracking)
    implementation(libs.palace.http.api)
    implementation(libs.rxandroid2)
    implementation(libs.rxjava2)
    implementation(libs.slf4j)
}
