dependencies {
    coreLibraryDesugaring(libs.android.desugaring)

    implementation(project(":palace-accounts-api"))
    implementation(project(":palace-bookmarks-api"))
    implementation(project(":palace-books-api"))
    implementation(project(":palace-books-database-api"))
    implementation(project(":palace-books-formats-api"))
    implementation(project(":palace-files"))
    implementation(project(":palace-json-core"))
    implementation(project(":palace-opds-core"))

    implementation(libs.google.failureaccess)
    implementation(libs.google.guava)
    implementation(libs.io7m.jnull)
    implementation(libs.irradia.mime.api)
    implementation(libs.jackson.core)
    implementation(libs.jackson.databind)
    implementation(libs.jcip.annotations)
    implementation(libs.joda.time)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.stdlib)
    implementation(libs.palace.audiobook.api)
    implementation(libs.palace.audiobook.manifest.api)
    implementation(libs.palace.audiobook.manifest.parser.api)
    implementation(libs.palace.audiobook.parser.api)
    implementation(libs.palace.drm.core)
    implementation(libs.slf4j)
}
