dependencies {
    coreLibraryDesugaring(libs.android.desugaring)

    implementation(project(":simplified-accessibility"))
    implementation(project(":simplified-accounts-api"))
    implementation(project(":simplified-accounts-database-api"))
    implementation(project(":simplified-analytics-api"))
    implementation(project(":simplified-bookmarks-api"))
    implementation(project(":simplified-books-api"))
    implementation(project(":simplified-books-controller-api"))
    implementation(project(":simplified-books-covers"))
    implementation(project(":simplified-books-database-api"))
    implementation(project(":simplified-books-formats-api"))
    implementation(project(":simplified-books-registry-api"))
    implementation(project(":simplified-feeds-api"))
    implementation(project(":simplified-mdc"))
    implementation(project(":simplified-opds-core"))
    implementation(project(":simplified-profiles-api"))
    implementation(project(":simplified-profiles-controller-api"))
    implementation(project(":simplified-reader-api"))
    implementation(project(":simplified-services-api"))
    implementation(project(":simplified-threads"))
    implementation(project(":simplified-ui-screen"))
    implementation(project(":simplified-viewer-spi"))
    implementation(project(":simplified-webview"))

    implementation(libs.irradia.mime.api)
    implementation(libs.slf4j)
}
