apply(plugin = "androidx.navigation.safeargs.kotlin")

fun getGitHash(): String {
    val proc = ProcessBuilder("git", "rev-parse", "--short", "HEAD")
        .redirectOutput(ProcessBuilder.Redirect.PIPE)
        .redirectError(ProcessBuilder.Redirect.PIPE)
        .start()

    proc.waitFor(10L, TimeUnit.SECONDS)
    return proc.inputStream.bufferedReader().readText().trim()
}

android {
    buildFeatures {
        dataBinding = true
        viewBinding = true
        buildConfig = true
    }

    defaultConfig {
        buildConfigField("String", "SIMPLIFIED_VERSION", "\"${rootProject.ext["VERSION_NAME"]}\"")
        buildConfigField("String", "SIMPLIFIED_GIT_COMMIT", "\"${getGitHash()}\"")
    }
}

dependencies {
    coreLibraryDesugaring(libs.android.desugaring)

    implementation(project(":simplified-accessibility"))
    implementation(project(":simplified-accounts-api"))
    implementation(project(":simplified-accounts-database"))
    implementation(project(":simplified-accounts-database-api"))
    implementation(project(":simplified-accounts-json"))
    implementation(project(":simplified-accounts-registry"))
    implementation(project(":simplified-accounts-registry-api"))
    implementation(project(":simplified-accounts-source-spi"))
    implementation(project(":simplified-adobe-extensions"))
    implementation(project(":simplified-analytics-api"))
    implementation(project(":simplified-announcements"))
    implementation(project(":simplified-bookmarks"))
    implementation(project(":simplified-bookmarks-api"))
    implementation(project(":simplified-books-api"))
    implementation(project(":simplified-books-audio"))
    implementation(project(":simplified-books-borrowing"))
    implementation(project(":simplified-books-bundled-api"))
    implementation(project(":simplified-books-controller"))
    implementation(project(":simplified-books-controller-api"))
    implementation(project(":simplified-books-covers"))
    implementation(project(":simplified-books-database-api"))
    implementation(project(":simplified-books-formats"))
    implementation(project(":simplified-books-formats-api"))
    implementation(project(":simplified-books-preview"))
    implementation(project(":simplified-books-registry-api"))
    implementation(project(":simplified-books-time-tracking"))
    implementation(project(":simplified-boot-api"))
    implementation(project(":simplified-buildconfig-api"))
    implementation(project(":simplified-content-api"))
    implementation(project(":simplified-crashlytics-api"))
    implementation(project(":simplified-documents"))
    implementation(project(":simplified-feeds-api"))
    implementation(project(":simplified-files"))
    implementation(project(":simplified-futures"))
    implementation(project(":simplified-lcp"))
    implementation(project(":simplified-links"))
    implementation(project(":simplified-mdc"))
    implementation(project(":simplified-notifications"))
    implementation(project(":simplified-oauth"))
    implementation(project(":simplified-opds-auth-document"))
    implementation(project(":simplified-opds-auth-document-api"))
    implementation(project(":simplified-opds-client"))
    implementation(project(":simplified-opds-core"))
    implementation(project(":simplified-patron"))
    implementation(project(":simplified-patron-api"))
    implementation(project(":simplified-presentableerror-api"))
    implementation(project(":simplified-profiles"))
    implementation(project(":simplified-profiles-api"))
    implementation(project(":simplified-profiles-controller-api"))
    implementation(project(":simplified-reader-api"))
    implementation(project(":simplified-reports"))
    implementation(project(":simplified-services-api"))
    implementation(project(":simplified-taskrecorder-api"))
    implementation(project(":simplified-tenprint"))
    implementation(project(":simplified-threads"))
    implementation(project(":simplified-ui-errorpage"))
    implementation(project(":simplified-ui-images"))
    implementation(project(":simplified-ui-screen"))
    implementation(project(":simplified-viewer-api"))
    implementation(project(":simplified-viewer-preview"))
    implementation(project(":simplified-viewer-spi"))
    implementation(project(":simplified-webview"))

    implementation(libs.androidx.activity)
    implementation(libs.androidx.activity.ktx)
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.appcompat.resources)
    implementation(libs.androidx.cardview)
    implementation(libs.androidx.collection)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.constraintlayout.core)
    implementation(libs.androidx.constraintlayout.solver)
    implementation(libs.androidx.coordinatorlayout)
    implementation(libs.androidx.core)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.customview)
    implementation(libs.androidx.customview.poolingcontainer)
    implementation(libs.androidx.drawerlayout)
    implementation(libs.androidx.emoji2)
    implementation(libs.androidx.emoji2.views)
    implementation(libs.androidx.emoji2.views.helper)
    implementation(libs.androidx.fragment)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.interpolator)
    implementation(libs.androidx.lifecycle.common)
    implementation(libs.androidx.lifecycle.extensions)
    implementation(libs.androidx.lifecycle.livedata)
    implementation(libs.androidx.lifecycle.livedata.core)
    implementation(libs.androidx.lifecycle.livedata.core.ktx)
    implementation(libs.androidx.lifecycle.livedata.ktx)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.androidx.lifecycle.viewmodel.savedstate)
    implementation(libs.androidx.paging.common)
    implementation(libs.androidx.paging.common.ktx)
    implementation(libs.androidx.paging.runtime)
    implementation(libs.androidx.paging.runtime.ktx)
    implementation(libs.androidx.preference)
    implementation(libs.androidx.recycler.view)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.savedstate)
    implementation(libs.androidx.swiperefreshlayout)
    implementation(libs.androidx.transition)
    implementation(libs.androidx.vectordrawable)
    implementation(libs.androidx.vectordrawable.animated)
    implementation(libs.androidx.viewpager2)
    implementation(libs.firebase.dynamic.links)
    implementation(libs.firebase.dynamic.links.ktx)
    implementation(libs.firebase.messaging)
    implementation(libs.firebase.messaging.ktx)
    implementation(libs.google.failureaccess)
    implementation(libs.google.guava)
    implementation(libs.google.material)
    implementation(libs.io7m.jattribute.core)
    implementation(libs.io7m.jfunctional)
    implementation(libs.io7m.jmulticlose)
    implementation(libs.io7m.jnull)
    implementation(libs.io7m.junreachable)
    implementation(libs.irradia.mime.api)
    implementation(libs.irradia.opds2.api)
    implementation(libs.irradia.opds2.lexical)
    implementation(libs.irradia.opds2.librarysimplified)
    implementation(libs.irradia.opds2.parser.api)
    implementation(libs.irradia.opds2.parser.extension.spi)
    implementation(libs.irradia.opds2.parser.librarysimplified)
    implementation(libs.irradia.opds2.parser.vanilla)
    implementation(libs.jackson.core)
    implementation(libs.jackson.databind)
    implementation(libs.jcip.annotations)
    implementation(libs.joda.time)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.stdlib)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.coroutines.core.jvm)
    implementation(libs.logback.android)
    implementation(libs.palace.audiobook.feedbooks)
    implementation(libs.palace.audiobook.time.tracking)
    implementation(libs.palace.audiobook.views)
    implementation(libs.palace.drm.core)
    implementation(libs.palace.http.api)
    implementation(libs.palace.http.bearer.token)
    implementation(libs.palace.http.vanilla)
    implementation(libs.palace.theme)
    implementation(libs.picasso)
    implementation(libs.play.services.base)
    implementation(libs.play.services.basement)
    implementation(libs.play.services.location)
    implementation(libs.play.services.tasks)
    implementation(libs.r2.lcp)
    implementation(libs.r2.shared)
    implementation(libs.rxandroid2)
    implementation(libs.rxjava2)
    implementation(libs.rxjava2.extensions)
    implementation(libs.slf4j)
    implementation(libs.transifex.sdk)
}
