fun getGitHash(): String {
    val proc = ProcessBuilder("git", "rev-parse", "--short", "HEAD")
        .redirectOutput(ProcessBuilder.Redirect.PIPE)
        .redirectError(ProcessBuilder.Redirect.PIPE)
        .start()

    proc.waitFor(10L, TimeUnit.SECONDS)
    return proc.inputStream.bufferedReader().readText().trim()
}

android {
    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        buildConfigField("String", "SIMPLIFIED_GIT_COMMIT", "\"${getGitHash()}\"")
        buildConfigField("String", "SIMPLIFIED_VERSION", "\"${rootProject.ext["VERSION_NAME"]}\"")
    }
}

dependencies {
    implementation(project(":simplified-accessibility"))
    implementation(project(":simplified-accounts-api"))
    implementation(project(":simplified-accounts-database"))
    implementation(project(":simplified-accounts-database-api"))
    implementation(project(":simplified-accounts-json"))
    implementation(project(":simplified-accounts-registry"))
    implementation(project(":simplified-accounts-registry-api"))
    implementation(project(":simplified-accounts-source-spi"))
    implementation(project(":simplified-adobe-extensions"))
    implementation(project(":simplified-analytics-api"))
    implementation(project(":simplified-android-ktx"))
    implementation(project(":simplified-announcements"))
    implementation(project(":simplified-bookmarks"))
    implementation(project(":simplified-bookmarks-api"))
    implementation(project(":simplified-books-api"))
    implementation(project(":simplified-books-audio"))
    implementation(project(":simplified-books-borrowing"))
    implementation(project(":simplified-books-bundled-api"))
    implementation(project(":simplified-books-controller"))
    implementation(project(":simplified-books-controller-api"))
    implementation(project(":simplified-books-covers"))
    implementation(project(":simplified-books-formats"))
    implementation(project(":simplified-books-formats-api"))
    implementation(project(":simplified-books-registry-api"))
    implementation(project(":simplified-books-time-tracking"))
    implementation(project(":simplified-boot-api"))
    implementation(project(":simplified-buildconfig-api"))
    implementation(project(":simplified-content-api"))
    implementation(project(":simplified-crashlytics-api"))
    implementation(project(":simplified-deeplinks-controller-api"))
    implementation(project(":simplified-documents"))
    implementation(project(":simplified-feeds-api"))
    implementation(project(":simplified-files"))
    implementation(project(":simplified-lcp"))
    implementation(project(":simplified-metrics"))
    implementation(project(":simplified-metrics-api"))
    implementation(project(":simplified-migration-api"))
    implementation(project(":simplified-migration-spi"))
    implementation(project(":simplified-networkconnectivity"))
    implementation(project(":simplified-networkconnectivity-api"))
    implementation(project(":simplified-notifications"))
    implementation(project(":simplified-oauth"))
    implementation(project(":simplified-opds-auth-document"))
    implementation(project(":simplified-opds-auth-document-api"))
    implementation(project(":simplified-opds-core"))
    implementation(project(":simplified-patron"))
    implementation(project(":simplified-patron-api"))
    implementation(project(":simplified-presentableerror-api"))
    implementation(project(":simplified-profiles"))
    implementation(project(":simplified-profiles-api"))
    implementation(project(":simplified-profiles-controller-api"))
    implementation(project(":simplified-reader-api"))
    implementation(project(":simplified-services-api"))
    implementation(project(":simplified-taskrecorder-api"))
    implementation(project(":simplified-tenprint"))
    implementation(project(":simplified-threads"))
    implementation(project(":simplified-ui-accounts"))
    implementation(project(":simplified-ui-announcements"))
    implementation(project(":simplified-ui-branding"))
    implementation(project(":simplified-ui-catalog"))
    implementation(project(":simplified-ui-errorpage"))
    implementation(project(":simplified-ui-images"))
    implementation(project(":simplified-ui-listeners-api"))
    implementation(project(":simplified-ui-navigation-tabs"))
    implementation(project(":simplified-ui-onboarding"))
    implementation(project(":simplified-ui-screen"))
    implementation(project(":simplified-ui-settings"))
    implementation(project(":simplified-ui-splash"))
    implementation(project(":simplified-ui-thread-api"))
    implementation(project(":simplified-ui-tutorial"))
    implementation(project(":simplified-viewer-api"))
    implementation(project(":simplified-viewer-audiobook"))
    implementation(project(":simplified-viewer-epub-readium2"))
    implementation(project(":simplified-viewer-pdf-pdfjs"))
    implementation(project(":simplified-viewer-preview"))
    implementation(project(":simplified-viewer-spi"))

    implementation(libs.androidx.activity)
    implementation(libs.androidx.activity.ktx)
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.cardview)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.coordinatorlayout)
    implementation(libs.androidx.core)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.customview)
    implementation(libs.androidx.drawerlayout)
    implementation(libs.androidx.fragment)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.lifecycle.common)
    implementation(libs.androidx.lifecycle.extensions)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.androidx.lifecycle.viewmodel.savedstate)
    implementation(libs.androidx.preference)
    implementation(libs.androidx.savedstate)
    implementation(libs.firebase.dynamic.links)
    implementation(libs.firebase.dynamic.links.ktx)
    implementation(libs.firebase.messaging)
    implementation(libs.firebase.messaging.ktx)
    implementation(libs.google.failureaccess)
    implementation(libs.google.guava)
    implementation(libs.google.material)
    implementation(libs.io7m.jnull)
    implementation(libs.irradia.mime.api)
    implementation(libs.irradia.mime.api)
    implementation(libs.irradia.opds2.api)
    implementation(libs.irradia.opds2.lexical)
    implementation(libs.irradia.opds2.librarysimplified)
    implementation(libs.irradia.opds2.parser.api)
    implementation(libs.irradia.opds2.parser.extension.spi)
    implementation(libs.irradia.opds2.parser.librarysimplified)
    implementation(libs.irradia.opds2.parser.vanilla)
    implementation(libs.jackson.core)
    implementation(libs.jackson.databind)
    implementation(libs.joda.time)
    implementation(libs.joda.time)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.stdlib)
    implementation(libs.kotlin.stdlib)
    implementation(libs.logback.android)
    implementation(libs.palace.audiobook.feedbooks)
    implementation(libs.palace.drm.core)
    implementation(libs.palace.http.api)
    implementation(libs.palace.http.bearer.token)
    implementation(libs.palace.http.vanilla)
    implementation(libs.palace.theme)
    implementation(libs.pandora.bottom.navigator)
    implementation(libs.picasso)
    implementation(libs.play.services.basement)
    implementation(libs.play.services.tasks)
    implementation(libs.r2.lcp)
    implementation(libs.rxandroid2)
    implementation(libs.rxjava2)
    implementation(libs.rxjava2.extensions)
    implementation(libs.slf4j)
    implementation(libs.slf4j)
    implementation(libs.transifex.sdk)
}
