dependencies {
    implementation(project(":simplified-json-core"))
    implementation(project(":simplified-links"))
    implementation(project(":simplified-links-json"))
    implementation(project(":simplified-parser-api"))

    implementation(libs.google.guava)
    implementation(libs.io7m.jfunctional)
    implementation(libs.io7m.jnull)
    implementation(libs.io7m.junreachable)
    implementation(libs.irradia.mime.api)
    implementation(libs.irradia.mime.vanilla)
    implementation(libs.jackson.core)
    implementation(libs.jackson.databind)
    implementation(libs.javax.annotation.api)
    implementation(libs.joda.time)
    implementation(libs.jsoup)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.stdlib)
    implementation(libs.slf4j)
}
